domain_path: C:\Users\ian_nolan1\Desktop\NewVitisWorkspace\Workspace\lab4_platform_2\export\lab4_platform_2\sw\standalone_microblaze_I
app_src_dir: C:\XilinxVitis\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
